links = [
  {
    "Investment": "Square",
    "Investor": "Goldman Sachs",
    "Target": 1,
    "Source": 40,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.3,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Square",
    "Investor": "Morgan Stanley",
    "Target": 1,
    "Source": 41,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0.24,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Square",
    "Investor": "Barclays",
    "Target": 1,
    "Source": 42,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0.24,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Square",
    "Investor": "JP Morgan Chase",
    "Target": 1,
    "Source": 43,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0.24,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Square",
    "Investor": "Citi",
    "Target": 1,
    "Source": 44,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.1,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "Square",
    "Investor": "Visa",
    "Target": 1,
    "Source": 45,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Square",
    "Investor": "SAP",
    "Target": 1,
    "Source": 46,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Square",
    "Investor": "Apple Pay",
    "Target": 1,
    "Source": 11,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Adyen",
    "Investor": "Android Pay",
    "Target": 2,
    "Source": 10,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "BrainTree",
    "Investor": "Android Pay",
    "Target": 3,
    "Source": 10,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Stripe",
    "Investor": "Android Pay",
    "Target": 4,
    "Source": 10,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Adyen",
    "Investor": "Deutsche Bank",
    "Target": 2,
    "Source": 47,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2006,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2006,
    "Duration Score": 0
  },
  {
    "Investment": "Adyen",
    "Investor": "Wells Fargo Bank",
    "Target": 2,
    "Source": 48,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2006,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2006,
    "Duration Score": 0
  },
  {
    "Investment": "Adyen",
    "Investor": "AliBaba",
    "Target": 2,
    "Source": 49,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Dwolla",
    "Investor": "BBVA",
    "Target": 5,
    "Source": 50,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Dwolla",
    "Investor": "Veridian Credit Iowa",
    "Target": 5,
    "Source": 51,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Dwolla",
    "Investor": "Microsoft",
    "Target": 5,
    "Source": 52,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Dwolla",
    "Investor": "Gates Foundation",
    "Target": 5,
    "Source": 53,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Dwolla",
    "Investor": "mFoundry",
    "Target": 5,
    "Source": 27,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.04000000000000001,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "Venmo",
    "Investor": "BrainTree",
    "Target": 6,
    "Source": 3,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0.32000000000000006,
    "Year": 2013,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2013,
    "Duration Score": 0.4
  },
  {
    "Investment": "PayPal",
    "Investor": "ING",
    "Target": 7,
    "Source": 54,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2001,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2001,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "Goldman Sachs",
    "Target": 7,
    "Source": 40,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2000,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2000,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "Providian Financial",
    "Target": 7,
    "Source": 8,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2001,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Providian Financial",
    "Investor": "JP Morgan Chase",
    "Target": 8,
    "Source": 43,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "Bankinter",
    "Target": 7,
    "Source": 55,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2001,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "Deutsche Bank",
    "Target": 7,
    "Source": 47,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2000,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2000,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "Apple",
    "Target": 7,
    "Source": 56,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "Citi",
    "Target": 7,
    "Source": 44,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "PayPal",
    "Investor": "JP Morgan Chase",
    "Target": 7,
    "Source": 43,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "PayPal",
    "Investor": "MasterCard",
    "Target": 7,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "PayPal",
    "Investor": "Visa",
    "Target": 7,
    "Source": 45,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "PayPal",
    "Investor": "Bank of America",
    "Target": 7,
    "Source": 58,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "PayPal",
    "Investor": "Samsung Pay",
    "Target": 7,
    "Source": 9,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "PayPal",
    "Investor": "Facebook",
    "Target": 7,
    "Source": 59,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "BitPay",
    "Target": 7,
    "Source": 60,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2014,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "PayPal",
    "Investor": "CoinBase",
    "Target": 7,
    "Source": 28,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Samsung Pay",
    "Investor": "HSBC",
    "Target": 9,
    "Source": 61,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Samsung Pay",
    "Investor": "Yes Bank",
    "Target": 9,
    "Source": 62,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Samsung Pay",
    "Investor": "Hang Seng Bank",
    "Target": 9,
    "Source": 63,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Samsung Pay",
    "Investor": "MasterCard",
    "Target": 9,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Samsung Pay",
    "Investor": "Visa",
    "Target": 9,
    "Source": 45,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Android Pay",
    "Investor": "PayPal",
    "Target": 10,
    "Source": 7,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Android Pay",
    "Investor": "Visa",
    "Target": 10,
    "Source": 45,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Android Pay",
    "Investor": "MasterCard",
    "Target": 10,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Apple Pay",
    "Investor": "MasterCard",
    "Target": 11,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Apple Pay",
    "Investor": "Visa",
    "Target": 11,
    "Source": 45,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Apple Pay",
    "Investor": "HSBC",
    "Target": 11,
    "Source": 61,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Visa Checkout",
    "Investor": "Android Pay",
    "Target": 12,
    "Source": 10,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Visa Checkout",
    "Investor": "Apple Pay",
    "Target": 12,
    "Source": 11,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "BitPesa",
    "Investor": "Bitbond",
    "Target": 13,
    "Source": 64,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "WorldRemit",
    "Investor": "JP Morgan Chase",
    "Target": 14,
    "Source": 43,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.5,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "WorldRemit",
    "Investor": "Silicon Valley Bank",
    "Target": 14,
    "Source": 65,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2016,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "WorldRemit",
    "Investor": "KCB Group",
    "Target": 14,
    "Source": 66,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "WorldRemit",
    "Investor": "UAE Exchange",
    "Target": 14,
    "Source": 67,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "WorldRemit",
    "Investor": "Huawei",
    "Target": 14,
    "Source": 68,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "WorldRemit",
    "Investor": "National Bank of Kuweit",
    "Target": 14,
    "Source": 69,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "WorldRemit",
    "Investor": "Android Pay",
    "Target": 14,
    "Source": 10,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "WorldRemit",
    "Investor": "MTN Group",
    "Target": 14,
    "Source": 70,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "BrainTree",
    "Investor": "PayPal",
    "Target": 3,
    "Source": 7,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2007,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2007,
    "Duration Score": 0
  },
  {
    "Investment": "BrainTree",
    "Investor": "SAP",
    "Target": 3,
    "Source": 46,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "BrainTree",
    "Investor": "Oracle",
    "Target": 3,
    "Source": 71,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "BrainTree",
    "Investor": "JP Morgan Chase",
    "Target": 3,
    "Source": 43,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.08000000000000002,
    "Year": 2013,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2013,
    "Duration Score": 0.4
  },
  {
    "Investment": "BrainTree",
    "Investor": "Wells Fargo Bank",
    "Target": 3,
    "Source": 48,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2007,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2007,
    "Duration Score": 0
  },
  {
    "Investment": "BrainTree",
    "Investor": "Apple Pay",
    "Target": 3,
    "Source": 11,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "BrainTree",
    "Investor": "Android Pay",
    "Target": 3,
    "Source": 10,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "BrainTree",
    "Investor": "CoinBase",
    "Target": 3,
    "Source": 28,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "BrainTree",
    "Investor": "Visa Checkout",
    "Target": 3,
    "Source": 12,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Klarna",
    "Investor": "Visa",
    "Target": 15,
    "Source": 45,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.5,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Sofort",
    "Investor": "Klarna",
    "Target": 16,
    "Source": 15,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2013,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "BillPay",
    "Investor": "Klarna",
    "Target": 17,
    "Source": 15,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Klarna",
    "Investor": "Adyen",
    "Target": 15,
    "Source": 2,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Klarna",
    "Investor": "WorldPay",
    "Target": 15,
    "Source": 72,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Klarna",
    "Investor": "Stripe",
    "Target": 15,
    "Source": 4,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 100,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Klarna",
    "Investor": "PPRO Group",
    "Target": 15,
    "Source": 73,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Azimo",
    "Investor": "Rakuten",
    "Target": 18,
    "Source": 74,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Azimo",
    "Investor": "Facebook",
    "Target": 18,
    "Source": 59,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Azimo",
    "Investor": "Vodafone",
    "Target": 18,
    "Source": 75,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Azimo",
    "Investor": "WorldPay",
    "Target": 18,
    "Source": 72,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Paydiant",
    "Investor": "PayPal",
    "Target": 19,
    "Source": 7,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0.6400000000000001,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Paydiant",
    "Investor": "Vantiv",
    "Target": 19,
    "Source": 76,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Paydiant",
    "Investor": "Barclays",
    "Target": 19,
    "Source": 42,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Paydiant",
    "Investor": "BankOne",
    "Target": 19,
    "Source": 77,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Stripe",
    "Investor": "Visa",
    "Target": 4,
    "Source": 45,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.4,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Stripe",
    "Investor": "American Express",
    "Target": 4,
    "Source": 78,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.4,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Stripe",
    "Investor": "AliBaba",
    "Target": 4,
    "Source": 49,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Stripe",
    "Investor": "MasterCard",
    "Target": 4,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Stripe",
    "Investor": "Visa",
    "Target": 4,
    "Source": 45,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Stripe",
    "Investor": "Amazon",
    "Target": 4,
    "Source": 79,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Stripe",
    "Investor": "Silicon Valley Bank",
    "Target": 4,
    "Source": 65,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "PayPal",
    "Target": 21,
    "Source": 7,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0.6400000000000001,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Xoom",
    "Investor": "Silicon Valley Bank",
    "Target": 21,
    "Source": 65,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Bancomer Transfer Services",
    "Target": 21,
    "Source": 80,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Westpac",
    "Target": 21,
    "Source": 81,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.04000000000000001,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "Xoom",
    "Investor": "Itaú Unibanco",
    "Target": 21,
    "Source": 82,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2010,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2010,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "National Bank of Pakistan",
    "Target": 21,
    "Source": 83,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Sampath Bank",
    "Target": 21,
    "Source": 84,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Allied Bank Limited",
    "Target": 21,
    "Source": 85,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "RCBC",
    "Target": 21,
    "Source": 86,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "LANDBANK",
    "Target": 21,
    "Source": 87,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Sacombank",
    "Target": 21,
    "Source": 88,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Banco Agricola",
    "Target": 21,
    "Source": 89,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2015,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Everest Bank Ltd",
    "Target": 21,
    "Source": 90,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "First Bank Nigeria",
    "Target": 21,
    "Source": 91,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Guaranty Trust Bank",
    "Target": 21,
    "Source": 92,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Xoom",
    "Investor": "Zenith Bank",
    "Target": 21,
    "Source": 93,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "iZettle",
    "Investor": "MasterCard",
    "Target": 22,
    "Source": 57,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.1,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "iZettle",
    "Investor": "American Express",
    "Target": 22,
    "Source": 78,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.1,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "iZettle",
    "Investor": "SEB Banka",
    "Target": 22,
    "Source": 94,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.3,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "iZettle",
    "Investor": "Santander",
    "Target": 22,
    "Source": 95,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.2,
    "Year": 2013,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2013,
    "Duration Score": 0.4
  },
  {
    "Investment": "iZettle",
    "Investor": "European Investment Bank",
    "Target": 22,
    "Source": 96,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "iZettle",
    "Investor": "Intel",
    "Target": 22,
    "Source": 97,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "iZettle",
    "Investor": "Nordea Bank",
    "Target": 22,
    "Source": 98,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "iZettle",
    "Investor": "DZ Bank",
    "Target": 22,
    "Source": 99,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.1,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "iZettle",
    "Investor": "EquensWordline",
    "Target": 22,
    "Source": 23,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "EquensWordline",
    "Investor": "ING",
    "Target": 23,
    "Source": 54,
    "Category": "owned-by",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "EquensWordline",
    "Investor": "Rabobank",
    "Target": 23,
    "Source": 100,
    "Category": "owned-by",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "EquensWordline",
    "Investor": "ABN Amro",
    "Target": 23,
    "Source": 101,
    "Category": "owned-by",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "EquensWordline",
    "Investor": "ICBPI",
    "Target": 23,
    "Source": 102,
    "Category": "owned-by",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "EquensWordline",
    "Investor": "DZ Bank",
    "Target": 23,
    "Source": 99,
    "Category": "owned-by",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "iZettle",
    "Investor": "Santander",
    "Target": 22,
    "Source": 95,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.08000000000000002,
    "Year": 2013,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2013,
    "Duration Score": 0.4
  },
  {
    "Investment": "iZettle",
    "Investor": "China UnionPay",
    "Target": 22,
    "Source": 103,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "iZettle",
    "Investor": "US Bankcorp",
    "Target": 22,
    "Source": 104,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "ShopKeep",
    "Investor": "WorldPay",
    "Target": 24,
    "Source": 72,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "Vantiv",
    "Target": 24,
    "Source": 76,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "TSYS",
    "Target": 24,
    "Source": 105,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "Global Payments",
    "Target": 24,
    "Source": 106,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "JP Morgan Chase",
    "Target": 24,
    "Source": 43,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "ShopKeep",
    "Investor": "First Data",
    "Target": 24,
    "Source": 107,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "US Bankcorp",
    "Target": 24,
    "Source": 104,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "ShopKeep",
    "Investor": "TransNational",
    "Target": 24,
    "Source": 108,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "C&H Financial Services",
    "Target": 24,
    "Source": 109,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "Nationwide Payments",
    "Target": 24,
    "Source": 110,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "ShopKeep",
    "Investor": "Apple Pay",
    "Target": 24,
    "Source": 11,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "ShopKeep",
    "Investor": "PayPal",
    "Target": 24,
    "Source": 7,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.04000000000000001,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "Remitly",
    "Investor": "PayU",
    "Target": 25,
    "Source": 111,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "International Finance Corporation",
    "Target": 25,
    "Source": 112,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Silicon Valley Bank",
    "Target": 25,
    "Source": 65,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "BDO Unibank",
    "Target": 25,
    "Source": 113,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Metrobank",
    "Target": 25,
    "Source": 114,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Philippine National Bank",
    "Target": 25,
    "Source": 115,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Bank of the Philippine Islands",
    "Target": 25,
    "Source": 116,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "ICICI Bank",
    "Target": 25,
    "Source": 117,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Citi",
    "Target": 25,
    "Source": 44,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "State Bank of India",
    "Target": 25,
    "Source": 118,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "HDFC Bank",
    "Target": 25,
    "Source": 119,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Axis Bank",
    "Target": 25,
    "Source": 120,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Credomatic",
    "Target": 25,
    "Source": 121,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Banrural",
    "Target": 25,
    "Source": 122,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Davivienda",
    "Target": 25,
    "Source": 123,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Bancolombia",
    "Target": 25,
    "Source": 124,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "BBVA",
    "Target": 25,
    "Source": 50,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Banpro",
    "Target": 25,
    "Source": 125,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Interbank",
    "Target": 25,
    "Source": 126,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Scotiabank",
    "Target": 25,
    "Source": 127,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Santander",
    "Target": 25,
    "Source": 95,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "HSBC",
    "Target": 25,
    "Source": 61,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Bank of America",
    "Target": 25,
    "Source": 58,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "Remitly",
    "Investor": "Bancomext",
    "Target": 25,
    "Source": 128,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "TransferWise",
    "Investor": "Starling Bank",
    "Target": 26,
    "Source": 33,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "TransferWise",
    "Investor": "CFSB",
    "Target": 26,
    "Source": 129,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "TransferWise",
    "Investor": "LHV",
    "Target": 26,
    "Source": 130,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "TransferWise",
    "Investor": "N26",
    "Target": 26,
    "Source": 31,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "TransferWise",
    "Investor": "Facebook",
    "Target": 26,
    "Source": 59,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "TransferWise",
    "Investor": "Pay Gate",
    "Target": 26,
    "Source": 131,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "TransferWise",
    "Investor": "Rocketbank",
    "Target": 26,
    "Source": 132,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "FIS",
    "Target": 27,
    "Source": 133,
    "Category": "acquisition",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "MasterCard",
    "Target": 27,
    "Source": 57,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "Intel",
    "Target": 27,
    "Source": 97,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "Motorola",
    "Target": 27,
    "Source": 134,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "Bank of America",
    "Target": 27,
    "Source": 58,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2008,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2008,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "NCR",
    "Target": 27,
    "Source": 135,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "PayPal",
    "Target": 27,
    "Source": 7,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "MasterCard",
    "Target": 27,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "ACI Worldwide",
    "Target": 27,
    "Source": 136,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "NEFCU",
    "Target": 27,
    "Source": 137,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "PayPal",
    "Target": 27,
    "Source": 7,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2011,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2011,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "Fidelity",
    "Target": 27,
    "Source": 138,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "Washington Trust Bank",
    "Target": 27,
    "Source": 139,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "mFoundry",
    "Investor": "Dwolla",
    "Target": 27,
    "Source": 5,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.04000000000000001,
    "Year": 2012,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2012,
    "Duration Score": 0.2
  },
  {
    "Investment": "Coinbase",
    "Investor": "Mitsubishi UFJ Financial Group",
    "Target": 28,
    "Source": 140,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.5,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Coinbase",
    "Investor": "USAA",
    "Target": 28,
    "Source": 141,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Coinbase",
    "Investor": "BBVA",
    "Target": 28,
    "Source": 50,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.4,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Coinbase",
    "Investor": "NYSE",
    "Target": 28,
    "Source": 142,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Coinbase",
    "Investor": "Shift Payments",
    "Target": 28,
    "Source": 143,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Coinbase",
    "Investor": "Bloomberg",
    "Target": 28,
    "Source": 144,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Coinbase",
    "Investor": "Microsoft",
    "Target": 28,
    "Source": 52,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Coinbase",
    "Investor": "PayPal",
    "Target": 28,
    "Source": 7,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Coinbase",
    "Investor": "Time Inc",
    "Target": 28,
    "Source": 145,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Coinbase",
    "Investor": "Square",
    "Target": 28,
    "Source": 1,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Coinbase",
    "Investor": "BrainTree",
    "Target": 28,
    "Source": 3,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.16000000000000003,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2015,
    "Duration Score": 0.8
  },
  {
    "Investment": "Coinbase",
    "Investor": "Mitsubishi UFJ Financial Group",
    "Target": 28,
    "Source": 140,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Coinbase",
    "Investor": "LHV",
    "Target": 28,
    "Source": 130,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.12,
    "Year": 2014,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2014,
    "Duration Score": 0.6
  },
  {
    "Investment": "Monzo",
    "Investor": "Stripe",
    "Target": 20,
    "Source": 4,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.5,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Monzo",
    "Investor": "Orange",
    "Target": 20,
    "Source": 146,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Monzo",
    "Investor": "MasterCard",
    "Target": 20,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 3,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Monzo",
    "Investor": "Jumio",
    "Target": 20,
    "Source": 147,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Chase Pay",
    "Investor": "JP Morgan Chase",
    "Target": 29,
    "Source": 43,
    "Category": "owned-by",
    "Type": "Directed",
    "Weight": 0,
    "Year": 2015,
    "Analysis": 1,
    "Partnership Size": 400,
    "Year Filtered": "",
    "Duration Score": 0
  },
  {
    "Investment": "Affirm",
    "Investor": "Morgan Stanley",
    "Target": 30,
    "Source": 41,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0.4,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Affirm",
    "Investor": "Oracle",
    "Target": 30,
    "Source": 71,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Affirm",
    "Investor": "Cross River Bank",
    "Target": 30,
    "Source": 148,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "Younited Credit",
    "Target": 31,
    "Source": 149,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "Auxmoney",
    "Target": 31,
    "Source": 150,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "Allianz",
    "Target": 31,
    "Source": 151,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2016,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "MasterCard",
    "Target": 31,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.08000000000000002,
    "Year": 2013,
    "Analysis": 1,
    "Partnership Size": 15,
    "Year Filtered": 2013,
    "Duration Score": 0.4
  },
  {
    "Investment": "N26",
    "Investor": "vaamo",
    "Target": 31,
    "Source": 152,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "FIL Fondsbank",
    "Target": 31,
    "Source": 153,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "Raisin",
    "Target": 31,
    "Source": 154,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "N26",
    "Investor": "MHB Bank",
    "Target": 31,
    "Source": 155,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Accenture",
    "Target": 32,
    "Source": 156,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "SBI Group",
    "Target": 32,
    "Source": 157,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Santander",
    "Target": 32,
    "Source": 95,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.5,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "Standard Chartered",
    "Target": 32,
    "Source": 158,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "CME Federal Credit Union",
    "Target": 32,
    "Source": 159,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Avant",
    "Target": 32,
    "Source": 160,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "American Express",
    "Target": 32,
    "Source": 78,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "ATB Financial",
    "Target": 32,
    "Source": 161,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "CIBC",
    "Target": 32,
    "Source": 162,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "NBAD",
    "Target": 32,
    "Source": 163,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Reisebank",
    "Target": 32,
    "Source": 164,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Santander",
    "Target": 32,
    "Source": 95,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "UniCredit",
    "Target": 32,
    "Source": 165,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "UBS",
    "Target": 32,
    "Source": 166,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "MUFG",
    "Target": 32,
    "Source": 167,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "BBVA",
    "Target": 32,
    "Source": 50,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "SEB Banka",
    "Target": 32,
    "Source": 94,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "Akbank",
    "Target": 32,
    "Source": 168,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Yes Bank",
    "Target": 32,
    "Source": 62,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "Axis Bank",
    "Target": 32,
    "Source": 120,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "SBI Group",
    "Target": 32,
    "Source": 157,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Star One Credit Union",
    "Target": 32,
    "Source": 169,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Mitsubishi UFJ Financial Group",
    "Target": 32,
    "Source": 140,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "Bank of America",
    "Target": 32,
    "Source": 58,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "Credit Agricole",
    "Target": 32,
    "Source": 170,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "Mizuho Financial Group",
    "Target": 32,
    "Source": 171,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "RBC",
    "Target": 32,
    "Source": 172,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Ripple",
    "Investor": "Westpac",
    "Target": 32,
    "Source": 81,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2017,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2017,
    "Duration Score": 1
  },
  {
    "Investment": "Ripple",
    "Investor": "BMO",
    "Target": 32,
    "Source": 173,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Starling Bank",
    "Investor": "Moneybox",
    "Target": 33,
    "Source": 174,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2017,
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Starling Bank",
    "Investor": "Form3",
    "Target": 33,
    "Source": 175,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Aspiration",
    "Investor": "Pomeroy",
    "Target": 34,
    "Source": 176,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Aspiration",
    "Investor": "REYL Bank",
    "Target": 34,
    "Source": 177,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Aspiration",
    "Investor": "Radius Bank",
    "Target": 34,
    "Source": 178,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Blockchain",
    "Investor": "Virgin Group",
    "Target": 35,
    "Source": 179,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Acorns",
    "Investor": "PayPal",
    "Target": 36,
    "Source": 7,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0.5,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Acorns",
    "Investor": "PayPal",
    "Target": 36,
    "Source": 7,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0.2,
    "Year": 2016,
    "Analysis": 1,
    "Partnership Size": 7,
    "Year Filtered": 2016,
    "Duration Score": 1
  },
  {
    "Investment": "Robinhood",
    "Investor": "Google",
    "Target": 37,
    "Source": 180,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Robinhood",
    "Investor": "Plaid",
    "Target": 37,
    "Source": 181,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Robinhood",
    "Investor": "APEX",
    "Target": 37,
    "Source": 182,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Robinhood",
    "Investor": "Baidu",
    "Target": 37,
    "Source": 183,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Payoneer",
    "Investor": "MasterCard",
    "Target": 38,
    "Source": 57,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": 2005,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2005,
    "Duration Score": 0
  },
  {
    "Investment": "Payoneer",
    "Investor": "Bank Asia",
    "Target": 38,
    "Source": 184,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Payoneer",
    "Investor": "Amazon",
    "Target": 38,
    "Source": 79,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "Payoneer",
    "Investor": "Rakuten",
    "Target": 38,
    "Source": 74,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "SoftBank",
    "Target": 39,
    "Source": 185,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "RenRen",
    "Target": 39,
    "Source": 186,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "SoftBank",
    "Target": 39,
    "Source": 185,
    "Category": "investment",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "East West Bank",
    "Target": 39,
    "Source": 187,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "Morgan Stanley",
    "Target": 39,
    "Source": 41,
    "Category": "debt",
    "Type": "Directed",
    "Weight": 0.16000000000000003,
    "Year": 2013,
    "Analysis": 1,
    "Partnership Size": 30,
    "Year Filtered": 2013,
    "Duration Score": 0.4
  },
  {
    "Investment": "SoFi",
    "Investor": "USI Affinity",
    "Target": 39,
    "Source": 188,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "WSFS Bank",
    "Target": 39,
    "Source": 189,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  },
  {
    "Investment": "SoFi",
    "Investor": "Fannie Mae",
    "Target": 39,
    "Source": 190,
    "Category": "partnership",
    "Type": "Undirected",
    "Weight": 0,
    "Year": "",
    "Analysis": 0,
    "Partnership Size": 0,
    "Year Filtered": 0,
    "Duration Score": 0
  }
  ];

  nodes =[
    {
        "Label": "Square",
        "Id": 1,
        "Type": "fintech"
      },
      {
        "Label": "Adyen",
        "Id": 2,
        "Type": "fintech"
      },
      {
        "Label": "BrainTree",
        "Id": 3,
        "Type": "fintech"
      },
      {
        "Label": "Stripe",
        "Id": 4,
        "Type": "fintech"
      },
      {
        "Label": "Dwolla",
        "Id": 5,
        "Type": "fintech"
      },
      {
        "Label": "Venmo",
        "Id": 6,
        "Type": "fintech"
      },
      {
        "Label": "PayPal",
        "Id": 7,
        "Type": "fintech"
      },
      {
        "Label": "Providian Financial",
        "Id": 8,
        "Type": "other"
      },
      {
        "Label": "Samsung Pay",
        "Id": 9,
        "Type": "fintech"
      },
      {
        "Label": "Android Pay",
        "Id": 10,
        "Type": "fintech"
      },
      {
        "Label": "Apple Pay",
        "Id": 11,
        "Type": "fintech"
      },
      {
        "Label": "Visa Checkout",
        "Id": 12,
        "Type": "fintech"
      },
      {
        "Label": "BitPesa",
        "Id": 13,
        "Type": "fintech"
      },
      {
        "Label": "WorldRemit",
        "Id": 14,
        "Type": "fintech"
      },
      {
        "Label": "Klarna",
        "Id": 15,
        "Type": "fintech"
      },
      {
        "Label": "Sofort",
        "Id": 16,
        "Type": "fintech"
      },
      {
        "Label": "BillPay",
        "Id": 17,
        "Type": "fintech"
      },
      {
        "Label": "Azimo",
        "Id": 18,
        "Type": "fintech"
      },
      {
        "Label": "Paydiant",
        "Id": 19,
        "Type": "fintech"
      },
      {
        "Label": "Monzo",
        "Id": 20,
        "Type": "fintech"
      },
      {
        "Label": "Xoom",
        "Id": 21,
        "Type": "fintech"
      },
      {
        "Label": "iZettle",
        "Id": 22,
        "Type": "fintech"
      },
      {
        "Label": "EquensWordline",
        "Id": 23,
        "Type": "other"
      },
      {
        "Label": "ShopKeep",
        "Id": 24,
        "Type": "fintech"
      },
      {
        "Label": "Remitly",
        "Id": 25,
        "Type": "fintech"
      },
      {
        "Label": "TransferWise",
        "Id": 26,
        "Type": "fintech"
      },
      {
        "Label": "mFoundry",
        "Id": 27,
        "Type": "fintech"
      },
      {
        "Label": "Coinbase",
        "Id": 28,
        "Type": "fintech"
      },
      {
        "Label": "Chase Pay",
        "Id": 29,
        "Type": "fintech"
      },
      {
        "Label": "Affirm",
        "Id": 30,
        "Type": "fintech"
      },
      {
        "Label": "N26",
        "Id": 31,
        "Type": "fintech"
      },
      {
        "Label": "Ripple",
        "Id": 32,
        "Type": "fintech"
      },
      {
        "Label": "Starling Bank",
        "Id": 33,
        "Type": "fintech"
      },
      {
        "Label": "Aspiration",
        "Id": 34,
        "Type": "fintech"
      },
      {
        "Label": "Blockchain",
        "Id": 35,
        "Type": "fintech"
      },
      {
        "Label": "Acorns",
        "Id": 36,
        "Type": "fintech"
      },
      {
        "Label": "Robinhood",
        "Id": 37,
        "Type": "fintech"
      },
      {
        "Label": "Payoneer",
        "Id": 38,
        "Type": "fintech"
      },
      {
        "Label": "SoFi",
        "Id": 39,
        "Type": "fintech"
      },
      {
        "Label": "Goldman Sachs",
        "Id": 40,
        "Type": "bigbank"
      },
      {
        "Label": "Morgan Stanley",
        "Id": 41,
        "Type": "bigbank"
      },
      {
        "Label": "Barclays",
        "Id": 42,
        "Type": "bigbank"
      },
      {
        "Label": "JP Morgan Chase",
        "Id": 43,
        "Type": "bigbank"
      },
      {
        "Label": "Citi",
        "Id": 44,
        "Type": "bigbank"
      },
      {
        "Label": "Visa",
        "Id": 45,
        "Type": "bigbank"
      },
      {
        "Label": "SAP",
        "Id": 46,
        "Type": "other"
      },
      {
        "Label": "Deutsche Bank",
        "Id": 47,
        "Type": "bigbank"
      },
      {
        "Label": "Wells Fargo Bank",
        "Id": 48,
        "Type": "bigbank"
      },
      {
        "Label": "AliBaba",
        "Id": 49,
        "Type": "other"
      },
      {
        "Label": "BBVA",
        "Id": 50,
        "Type": "bigbank"
      },
      {
        "Label": "Veridian Credit Iowa",
        "Id": 51,
        "Type": "other"
      },
      {
        "Label": "Microsoft",
        "Id": 52,
        "Type": "other"
      },
      {
        "Label": "Gates Foundation",
        "Id": 53,
        "Type": "other"
      },
      {
        "Label": "ING",
        "Id": 54,
        "Type": "bigbank"
      },
      {
        "Label": "Bankinter",
        "Id": 55,
        "Type": "other"
      },
      {
        "Label": "Apple",
        "Id": 56,
        "Type": "other"
      },
      {
        "Label": "MasterCard",
        "Id": 57,
        "Type": "bigbank"
      },
      {
        "Label": "Bank of America",
        "Id": 58,
        "Type": "bigbank"
      },
      {
        "Label": "Facebook",
        "Id": 59,
        "Type": "other"
      },
      {
        "Label": "BitPay",
        "Id": 60,
        "Type": "fintech"
      },
      {
        "Label": "HSBC",
        "Id": 61,
        "Type": "bigbank"
      },
      {
        "Label": "Yes Bank",
        "Id": 62,
        "Type": "other"
      },
      {
        "Label": "Hang Seng Bank",
        "Id": 63,
        "Type": "other"
      },
      {
        "Label": "Bitbond",
        "Id": 64,
        "Type": "fintech"
      },
      {
        "Label": "Silicon Valley Bank",
        "Id": 65,
        "Type": "other"
      },
      {
        "Label": "KCB Group",
        "Id": 66,
        "Type": "other"
      },
      {
        "Label": "UAE Exchange",
        "Id": 67,
        "Type": "other"
      },
      {
        "Label": "Huawei",
        "Id": 68,
        "Type": "other"
      },
      {
        "Label": "National Bank of Kuweit",
        "Id": 69,
        "Type": "other"
      },
      {
        "Label": "MTN Group",
        "Id": 70,
        "Type": "other"
      },
      {
        "Label": "Oracle",
        "Id": 71,
        "Type": "other"
      },
      {
        "Label": "WorldPay",
        "Id": 72,
        "Type": "other"
      },
      {
        "Label": "PPRO Group",
        "Id": 73,
        "Type": "other"
      },
      {
        "Label": "Rakuten",
        "Id": 74,
        "Type": "other"
      },
      {
        "Label": "Vodafone",
        "Id": 75,
        "Type": "other"
      },
      {
        "Label": "Vantiv",
        "Id": 76,
        "Type": "other"
      },
      {
        "Label": "BankOne",
        "Id": 77,
        "Type": "other"
      },
      {
        "Label": "American Express",
        "Id": 78,
        "Type": "bigbank"
      },
      {
        "Label": "Amazon",
        "Id": 79,
        "Type": "other"
      },
      {
        "Label": "Bancomer Transfer Services",
        "Id": 80,
        "Type": "other"
      },
      {
        "Label": "Westpac",
        "Id": 81,
        "Type": "bigbank"
      },
      {
        "Label": "Itaú Unibanco",
        "Id": 82,
        "Type": "bigbank"
      },
      {
        "Label": "National Bank of Pakistan",
        "Id": 83,
        "Type": "other"
      },
      {
        "Label": "Sampath Bank",
        "Id": 84,
        "Type": "other"
      },
      {
        "Label": "Allied Bank Limited",
        "Id": 85,
        "Type": "other"
      },
      {
        "Label": "RCBC",
        "Id": 86,
        "Type": "other"
      },
      {
        "Label": "LANDBANK",
        "Id": 87,
        "Type": "other"
      },
      {
        "Label": "Sacombank",
        "Id": 88,
        "Type": "other"
      },
      {
        "Label": "Banco Agricola",
        "Id": 89,
        "Type": "bigbank"
      },
      {
        "Label": "Everest Bank Ltd",
        "Id": 90,
        "Type": "other"
      },
      {
        "Label": "First Bank Nigeria",
        "Id": 91,
        "Type": "other"
      },
      {
        "Label": "Guaranty Trust Bank",
        "Id": 92,
        "Type": "other"
      },
      {
        "Label": "Zenith Bank",
        "Id": 93,
        "Type": "other"
      },
      {
        "Label": "SEB Banka",
        "Id": 94,
        "Type": "bigbank"
      },
      {
        "Label": "Santander",
        "Id": 95,
        "Type": "bigbank"
      },
      {
        "Label": "European Investment Bank",
        "Id": 96,
        "Type": "bigbank"
      },
      {
        "Label": "Intel",
        "Id": 97,
        "Type": "other"
      },
      {
        "Label": "Nordea Bank",
        "Id": 98,
        "Type": "other"
      },
      {
        "Label": "DZ Bank",
        "Id": 99,
        "Type": "bigbank"
      },
      {
        "Label": "Rabobank",
        "Id": 100,
        "Type": "bigbank"
      },
      {
        "Label": "ABN Amro",
        "Id": 101,
        "Type": "bigbank"
      },
      {
        "Label": "ICBPI",
        "Id": 102,
        "Type": "other"
      },
      {
        "Label": "China UnionPay",
        "Id": 103,
        "Type": "other"
      },
      {
        "Label": "US Bankcorp",
        "Id": 104,
        "Type": "bigbank"
      },
      {
        "Label": "TSYS",
        "Id": 105,
        "Type": "other"
      },
      {
        "Label": "Global Payments",
        "Id": 106,
        "Type": "other"
      },
      {
        "Label": "First Data",
        "Id": 107,
        "Type": "other"
      },
      {
        "Label": "TransNational",
        "Id": 108,
        "Type": "other"
      },
      {
        "Label": "C&H Financial Services",
        "Id": 109,
        "Type": "other"
      },
      {
        "Label": "Nationwide Payments",
        "Id": 110,
        "Type": "other"
      },
      {
        "Label": "PayU",
        "Id": 111,
        "Type": "other"
      },
      {
        "Label": "International Finance Corporation",
        "Id": 112,
        "Type": "other"
      },
      {
        "Label": "BDO Unibank",
        "Id": 113,
        "Type": "other"
      },
      {
        "Label": "Metrobank",
        "Id": 114,
        "Type": "other"
      },
      {
        "Label": "Philippine National Bank",
        "Id": 115,
        "Type": "other"
      },
      {
        "Label": "Bank of the Philippine Islands",
        "Id": 116,
        "Type": "other"
      },
      {
        "Label": "ICICI Bank",
        "Id": 117,
        "Type": "other"
      },
      {
        "Label": "State Bank of India",
        "Id": 118,
        "Type": "other"
      },
      {
        "Label": "HDFC Bank",
        "Id": 119,
        "Type": "other"
      },
      {
        "Label": "Axis Bank",
        "Id": 120,
        "Type": "other"
      },
      {
        "Label": "Credomatic",
        "Id": 121,
        "Type": "other"
      },
      {
        "Label": "Banrural",
        "Id": 122,
        "Type": "other"
      },
      {
        "Label": "Davivienda",
        "Id": 123,
        "Type": "other"
      },
      {
        "Label": "Bancolombia",
        "Id": 124,
        "Type": "other"
      },
      {
        "Label": "Banpro",
        "Id": 125,
        "Type": "other"
      },
      {
        "Label": "Interbank",
        "Id": 126,
        "Type": "other"
      },
      {
        "Label": "Scotiabank",
        "Id": 127,
        "Type": "other"
      },
      {
        "Label": "Bancomext",
        "Id": 128,
        "Type": "other"
      },
      {
        "Label": "CFSB",
        "Id": 129,
        "Type": "other"
      },
      {
        "Label": "LHV",
        "Id": 130,
        "Type": "other"
      },
      {
        "Label": "Pay Gate",
        "Id": 131,
        "Type": "other"
      },
      {
        "Label": "Rocketbank",
        "Id": 132,
        "Type": "other"
      },
      {
        "Label": "FIS",
        "Id": 133,
        "Type": "other"
      },
      {
        "Label": "Motorola",
        "Id": 134,
        "Type": "other"
      },
      {
        "Label": "NCR",
        "Id": 135,
        "Type": "other"
      },
      {
        "Label": "ACI Worldwide",
        "Id": 136,
        "Type": "other"
      },
      {
        "Label": "NEFCU",
        "Id": 137,
        "Type": "other"
      },
      {
        "Label": "Fidelity",
        "Id": 138,
        "Type": "other"
      },
      {
        "Label": "Washington Trust Bank",
        "Id": 139,
        "Type": "other"
      },
      {
        "Label": "Mitsubishi UFJ Financial Group",
        "Id": 140,
        "Type": "bigbank"
      },
      {
        "Label": "USAA",
        "Id": 141,
        "Type": "other"
      },
      {
        "Label": "NYSE",
        "Id": 142,
        "Type": "bigbank"
      },
      {
        "Label": "Shift Payments",
        "Id": 143,
        "Type": "other"
      },
      {
        "Label": "Bloomberg",
        "Id": 144,
        "Type": "other"
      },
      {
        "Label": "Time Inc",
        "Id": 145,
        "Type": "other"
      },
      {
        "Label": "Orange",
        "Id": 146,
        "Type": "other"
      },
      {
        "Label": "Jumio",
        "Id": 147,
        "Type": "other"
      },
      {
        "Label": "Cross River Bank",
        "Id": 148,
        "Type": "other"
      },
      {
        "Label": "Younited Credit",
        "Id": 149,
        "Type": "other"
      },
      {
        "Label": "Auxmoney",
        "Id": 150,
        "Type": "other"
      },
      {
        "Label": "Allianz",
        "Id": 151,
        "Type": "bigbank"
      },
      {
        "Label": "vaamo",
        "Id": 152,
        "Type": "other"
      },
      {
        "Label": "FIL Fondsbank",
        "Id": 153,
        "Type": "other"
      },
      {
        "Label": "Raisin",
        "Id": 154,
        "Type": "other"
      },
      {
        "Label": "MHB Bank",
        "Id": 155,
        "Type": "other"
      },
      {
        "Label": "Accenture",
        "Id": 156,
        "Type": "other"
      },
      {
        "Label": "SBI Group",
        "Id": 157,
        "Type": "other"
      },
      {
        "Label": "Standard Chartered",
        "Id": 158,
        "Type": "other"
      },
      {
        "Label": "CME Federal Credit Union",
        "Id": 159,
        "Type": "other"
      },
      {
        "Label": "Avant",
        "Id": 160,
        "Type": "other"
      },
      {
        "Label": "ATB Financial",
        "Id": 161,
        "Type": "other"
      },
      {
        "Label": "CIBC",
        "Id": 162,
        "Type": "other"
      },
      {
        "Label": "NBAD",
        "Id": 163,
        "Type": "other"
      },
      {
        "Label": "Reisebank",
        "Id": 164,
        "Type": "other"
      },
      {
        "Label": "UniCredit",
        "Id": 165,
        "Type": "other"
      },
      {
        "Label": "UBS",
        "Id": 166,
        "Type": "bigbank"
      },
      {
        "Label": "MUFG",
        "Id": 167,
        "Type": "other"
      },
      {
        "Label": "Akbank",
        "Id": 168,
        "Type": "other"
      },
      {
        "Label": "Star One Credit Union",
        "Id": 169,
        "Type": "other"
      },
      {
        "Label": "Credit Agricole",
        "Id": 170,
        "Type": "bigbank"
      },
      {
        "Label": "Mizuho Financial Group",
        "Id": 171,
        "Type": "other"
      },
      {
        "Label": "RBC",
        "Id": 172,
        "Type": "other"
      },
      {
        "Label": "BMO",
        "Id": 173,
        "Type": "other"
      },
      {
        "Label": "Moneybox",
        "Id": 174,
        "Type": "fintech"
      },
      {
        "Label": "Form3",
        "Id": 175,
        "Type": "other"
      },
      {
        "Label": "Pomeroy",
        "Id": 176,
        "Type": "other"
      },
      {
        "Label": "REYL Bank",
        "Id": 177,
        "Type": "other"
      },
      {
        "Label": "Radius Bank",
        "Id": 178,
        "Type": "other"
      },
      {
        "Label": "Virgin Group",
        "Id": 179,
        "Type": "other"
      },
      {
        "Label": "Google",
        "Id": 180,
        "Type": "other"
      },
      {
        "Label": "Plaid",
        "Id": 181,
        "Type": "other"
      },
      {
        "Label": "APEX",
        "Id": 182,
        "Type": "other"
      },
      {
        "Label": "Baidu",
        "Id": 183,
        "Type": "other"
      },
      {
        "Label": "Bank Asia",
        "Id": 184,
        "Type": "other"
      },
      {
        "Label": "SoftBank",
        "Id": 185,
        "Type": "other"
      },
      {
        "Label": "RenRen",
        "Id": 186,
        "Type": "other"
      },
      {
        "Label": "East West Bank",
        "Id": 187,
        "Type": "other"
      },
      {
        "Label": "USI Affinity",
        "Id": 188,
        "Type": "other"
      },
      {
        "Label": "WSFS Bank",
        "Id": 189,
        "Type": "other"
      },
      {
        "Label": "Fannie Mae",
        "Id": 190,
        "Type": "other"
      },
      {
        "Label": "",
        "Id": "",
        "Type": ""
      }
  ];